name: Scrape Stock Data
on: [push, schedule]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install # Only install npm dependencies; Puppeteer will handle browser download
    - name: Run scraper
      timeout-minutes: 15
      run: node scraper.js
      env:
        # Set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD to false to ensure Puppeteer downloads Chrome if not found.
        # No need for explicit 'npx puppeteer install' if this is set to false.
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: false
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: stock-data
        path: debug_*.png
